version: "3.8"
services:
  flask-app:
    image: duo-app:v2
    build: .
    deploy:
      replicas: 3
    networks:
      - duo-net
  nginx:
    image: nginx:alpine
    networks:
      - duo-net
    ports:
      - target: 80
        published: 80
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
    depends_on:
      - flask-app
networks:
  duo-net:
